language: java

env:
  global:
    - TERM=dumb
    - ANDROID_SDK_VERSION="r23"

sudo: false
before_install:
  - chmod +x ./gradlew
  - wget http://dl.google.com/android/android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - tar -zxf android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo yes | android update sdk --filter extra-android-support --no-ui --force
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force
  - echo yes | android update sdk --filter extra-google-m2repository --no-ui --force
  - echo yes | android update sdk --filter platform-tools --no-ui --force
  - echo yes | android update sdk --filter platform-tool --no-ui --force
  - echo yes | android update sdk --all --filter build-tools-23.0.2 --no-ui --force
  - echo yes | android update sdk --all --filter build-tool-23.0.2 --no-ui --force
  - echo yes | android update sdk --filter android-23 --no-ui --force
  - echo "Getting list of android sdk options"
  - android list sdk -a

install:
  - TERM=dumb ./gradlew assemble --stacktrace --info

script:
  - TERM=dumb ./gradlew check --stacktrace --info