language: java

env:
  global:
    - TERM=dumb
    - ANDROID_SDK_VERSION="r24.4.1"

sudo: false
before_install:
  - chmod +x ./gradlew
  - wget http://dl.google.com/android/android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - tar -zxf android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-google-m2repository --no-ui --force > /dev/null
  - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
  - echo yes | android update sdk --all --filter build-tools-23.0.2 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter android-23 --no-ui --force > /dev/null

install:
  - TERM=dumb ./gradlew assemble --stacktrace --info

script:
#  - travis_wait ./gradlew check --stacktrace --info
  - ./gradlew check --stacktrace --debug