language: java

env:
  global:
    - TERM=dumb
    - ANDROID_SDK_VERSION="r24.4.1"

sudo: false
before_install:
  - chmod +x ./gradlew
  - wget http://dl.google.com/android/android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - tar -zxf android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-google-m2repository --no-ui --force > /dev/null
  - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
  - echo yes | android update sdk --all --filter build-tools-23.0.2 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter android-23 --no-ui --force > /dev/null

install:
  - TERM=dumb ./gradlew assemble --stacktrace --info

script:
#  - travis_wait ./gradlew check --stacktrace --info
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.passing test without missing dep\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.tasks list without missing dep\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.tasks list with resolvable dep\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.failing build with missing dep without git extension\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.failing one build with missing dep with git extension\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.passing build twice with missing dep with git extension\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.passing build twice with missing dep with git extension initGitDependencies\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.fail first build missing dep using git direct call initGitDependencies\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.fail build missing dep using git direct call initGitDependencies wrong commit\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.fail build missing dep using git direct call initGitDependencies branch\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.pass build twice missing dep using git direct call listGitDependencies branch\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.pass build twice missing dep using git direct call listGitDependencies tag\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.pass build twice missing dep using git direct call initGitDependencies branch keepUpdated\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.initGitDependencies dep without git gitConfig\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.passing test dep with git gitConfig\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.passing multi dep with one git\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.passing multi dep with both git\" --stacktrace
  - ./gradlew cleanTest test --tests \"com.testfunction.AndroidLibraryTest.failing test dep non existent\" --stacktrace