package com.testfunction

/**
 * Test dependency types
 *
 * Created by Brandon on 1/4/2016.
 */
enum TestTypes {
    DEPENDENCY_NONE,
    DEPENDENCY_WITHOUT_GIT,
    DEPENDENCY_WITH_GIT,
    DEPENDENCY_WITH_GIT_COMMIT,
    DEPENDENCY_WITH_GIT_COMMIT_WRONG,
    DEPENDENCY_WITH_GIT_TAG,
    DEPENDENCY_WITH_GIT_BRANCH,
    DEPENDENCY_WITH_GIT_BRANCH_KEEP_UPDATED,
    DEPENDENCY_WITH_GIT_BRANCH_LIST_DEPENDENCIES,
    DEPENDENCY_WITH_GIT_AUTOMATIC_RESOLVE,
    DEPENDENCY_WITHOUT_GIT_DIFF_CONFIG,
    DEPENDENCY_WITH_GIT_DIFF_CONFIG,
    DEPENDENCY_MULTIPLE_WITH_ONE_GIT,
    DEPENDENCY_MULTIPLE_WITH_ALL_GIT,
    DEPENDENCY_NON_EXISTENT

}